# Generated by Django 4.2.2 on 2023-08-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_draft_alter_actor_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='Возраст'),
        ),
    ]
